from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),
    path('gallery/', views.gallery),
    path('blogdelhi/',views.blogdelhi),
    path('blogbangalore/',views.blogbangalore),
    path('blogpune/',views.blogpune),
    path('blogmumbai/',views.blogmumbai),
    path('bloghyderabad/',views.bloghyderabad),
    path('blogchennai/',views.blogchennai),
    path('signup/', views.register_request, name="register"),
    path("signup/login", views.login_request, name="login"),
    path("message/", views.message),
    path("signup/index/", views.index),
    path("signup/index/trains/", views.trains),
    path("signup/index/flights/", views.flights),
    path("signup/index/cars/", views.cars),
    path("signup/index/main/", views.main),
    path("signup/index/home1/", views.index1),
    path("signup/index/home2/", views.index2),
    path("signup/index/home3/", views.index3),
    path("signup/index/compare/", views.compare),
    path("signup/index/main/delhi/", views.delhi),
    path("signup/index/main/delhi/travel/", views.delhi_travel),
    path("signup/index/main/delhi/security/", views.delhi_security),
    path("signup/index/main/delhi/tours/", views.delhi_tours),
    path("signup/index/main/delhi/hotels/", views.delhi_hotels),
    path("signup/index/main/delhi/hotels/hotelbook/", views.hotel_book),
    path("signup/index/main/bangalore/hotels/hotelbook/", views.hotel_book),
    path("signup/index/main/chennai/hotels/hotelbook/", views.hotel_book),
    path("signup/index/main/hyderabad/hotels/hotelbook/", views.hotel_book),
    path("signup/index/main/kolkata/hotels/hotelbook/", views.hotel_book),
    path("signup/index/main/jammu/hotels/hotelbook/", views.hotel_book),
    path("signup/index/main/jammu/", views.jammu),
    path("signup/index/main/jammu/travel/", views.jammu_travel),
    path("signup/index/main/jammu/security/", views.jammu_security),
    path("signup/index/main/jammu/tours/", views.jammu_tours),
    path("signup/index/main/jammu/hotels/", views.jammu_hotels),
    path("signup/index/main/kerala/", views.kerala),
    path("signup/index/main/kerala/travel/", views.kerala_travel),
    path("signup/index/main/kerala/security/", views.kerala_security),
    path("signup/index/main/kerala/tours/", views.kerala_tours),
    path("signup/index/main/kerala/hotels/", views.kerala_hotels),
    path("signup/index/main/mumbai/", views.mumbai),
    path("signup/index/main/mumbai/travel/", views.mumbai_travel),
    path("signup/index/main/mumbai/security/", views.mumbai_security),
    path("signup/index/main/mumbai/tours/", views.mumbai_tours),
    path("signup/index/main/mumbai/hotels/", views.mumbai_hotels),
    path("signup/index/main/bangalore/", views.bangalore),
    path("signup/index/main/bangalore/travel/", views.bangalore_travel),
    path("signup/index/main/bangalore/security/", views.bangalore_security),
    path("signup/index/main/bangalore/tours/", views.bangalore_tours),
    path("signup/index/main/bangalore/hotels/", views.bangalore_hotels),
    path("signup/index/main/chennai/", views.chennai),
    path("signup/index/main/chennai/travel/", views.chennai_travel),
    path("signup/index/main/chennai/security/", views.chennai_security),
    path("signup/index/main/chennai/tours/", views.chennai_tours),
    path("signup/index/main/chennai/hotels/", views.chennai_hotels),
    path("payment/", views.payment),
    path("bot/", views.bot),
    path("logout", views.logout_request, name="logout"),
]
