# Generated by Django 3.1.7 on 2021-05-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210516_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
